version: "3.7"

services:
  database:
    image: postgres
    container_name: security-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security
    ports:
      - '5432:5432'
    restart: always
  app:
    build:
      dockerfile: Dockerfile
    container_name: spring-security
    expose:
      - 8080
    ports:
      - '8080:8080'
    links:
      - database
    depends_on:
      - database
