version: "3.7"

services:
  database:
    image: postgres
    container_name: security-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security
    ports:
      - '5432:5432'
    restart: always
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_MAIL_USERNAME: ${EMAIL_NAME}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}
    container_name: spring-security
    expose:
      - 8080
    ports:
      - '8080:8080'
    links:
      - database
    depends_on:
      - database
