version: "3.7"

services:
  database:
    image: postgres
    container_name: grocery-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grocery
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    container_name: grocery
    ports:
      - 8080:8080
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database
